version: '3'

services:
  php-workflow-demo:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: php-workflow-demo
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
    networks:
      - uptilt

networks:
  uptilt:
    external:
      name: uptilt