version: 2

jobs:
  run-tests:
    docker:
      - image: circleci/php:7.3
    steps:
      - checkout
      - run: composer install --no-interaction --no-suggest
      - run: php artisan key:generate --env=testing
      - run: ./vendor/bin/phpunit

  # Branch Jobs
  build-branch:
    machine: true
    steps:
      - checkout
      - run: docker login $DOCKER_SERVER -u $DOCKER_USER -p $DOCKER_PASS
      # Build the application image.
      - run: docker build -t $DOCKER_SERVER/defrostedtuna/php-workflow-demo:$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7) .
      # Upload the image to the registry.
      - run: docker push $DOCKER_SERVER/defrostedtuna/php-workflow-demo:$CIRCLE_BRANCH-$(echo $CIRCLE_SHA1 | cut -c -7)

  # Tag Jobs
  build-tag:
    machine: true
    steps:
      - checkout
      - run: docker login $DOCKER_SERVER -u $DOCKER_USER -p $DOCKER_PASS
      # Build the application image.
      - run: docker build -t $DOCKER_SERVER/defrostedtuna/php-workflow-demo:$CIRCLE_TAG .
      # Upload the image to the registry.
      - run: docker push $DOCKER_SERVER/defrostedtuna/php-workflow-demo:$CIRCLE_TAG

  release:
    machine: true
    steps:
      - echo "This is where the release will be done."

workflows:
  version: 2

  build-branch:
    jobs:
      - run-tests:
          filters:
            branches:
              only: /master|develop/
            tags:
              ignore: /.*/
      - build-branch:
          requires:
            - run-tests
          filters:
            branches:
              only: /master|develop/
            tags:
              ignore: /.*/
      - release:
          requires:
            - run-tests
            - build-branch
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/

  build-tag:
    jobs:
      - run-tests:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - build-tag:
          requires:
            - run-tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/